feat: multi language filter and cdk type filter
cdklabs/construct-hub-webapp pull request #438
Opened 2021-09-28 19:48 UTC by gabewomble

Fixes #

This PR is still a work in progress, based off of work setup by the parent PR #433 

Here's a summary of changes:
- New Search Page supports multi-language filtering, meaning any construct that matches one of the selected languages will be a result (assuming its not filtered out by other filters)
- New Search Page supports cdkType filtering. This work is not final as the catalog.json does not yet return that information
- To preserve backwards compatibility with the old search page, the multi language filter has a separate query param and function param

2021-09-28 19:50 UTC, gabewomble commented on src/views/SearchRedesign/SearchResults.tsx
> -  const queryParams = useQueryParams();
A lot of this page-level state has been hoisted to `SearchState.tsx` which implements a react context for components on the page to subscribe to

2021-09-29 18:16 UTC, Chriscbr requested changes

2021-09-29 18:39 UTC, gabewomble commented on src/views/SearchRedesign/SearchState.tsx
> +export const useSearchState = () => {
Yeah I can definitely do that! `useSearchState` is specific to the Search view, although the rest are actually generic (if they are in `src/hooks`)

2021-09-29 20:20 UTC, Chriscbr approved these changes

2021-09-29 20:20 UTC, merged